<?php
// Theme localization Fields
if( !function_exists('foodzone_localization') )
{
    function foodzone_localization()
	{
		global $localization;
		//global $foodzone_options;
        $localization = array
	    (
		    'keyword' => esc_html__('Keyword','foodzone'),
	   		'property_type' => esc_html__('Property Type','foodzone'),
			'property_stat' => esc_html__('Property Status','foodzone'),
			'offer_type' 	=> esc_html__('Offer Type','foodzone'),
			'property_label' => esc_html__('Label','foodzone'),
			'currecny_type' => esc_html__('Currency Type','foodzone'),
			'property_price' => esc_html__('Property Price','foodzone'),
			'snd_price' 	=> esc_html__('Second Price (Optional)','foodzone'),
			'before_price' => esc_html__('Before Price Label','foodzone'),
			'after_price' => esc_html__('After Price Label','foodzone'),
			'property_area' => esc_html__('Area Size','foodzone'),
			'area_prefix' => esc_html__('Area Size Prefix ','foodzone'),
			'land_area' => esc_html__('Land Area','foodzone'),
			'land_area_prefix' => esc_html__('Land Area Prefix','foodzone'),
			'bedrooms' => esc_html__('Bedrooms','foodzone'),
			'bathrooms' => esc_html__('Bathrooms','foodzone'),
			'grages' => esc_html__('Garages','foodzone'),
			'yearbuild' => esc_html__('Year Built','foodzone'),
			'amenities' => esc_html__('Amenities and Features','foodzone'),
			'video' => esc_html__('Video URL','foodzone'),
			'virtual_tour' => esc_html__('360 Virtual Tour Iframe','foodzone'),
			'desc' => esc_html__('Description Box','foodzone'),
			'gallery' => esc_html__('Gallery','foodzone'),
			'zip_code' => esc_html__('Zipcode','foodzone'),
			'street_location' => esc_html__('Street Address','foodzone'),
			'map' => esc_html__('Map','foodzone'),
			'coordinates' => esc_html__('Coordinates','foodzone'),
			'location' => esc_html__('Location (Country / State / Town)','foodzone'),
			'floorplan' => esc_html__('Floor Plans','foodzone'),
			'additional_fields' => esc_html__('Additional Fields','foodzone'),
			'attachments' => esc_html__('Attachments','foodzone'),
			'dashboard' => esc_html__('Dashboard','foodzone'),
			'profile' => esc_html__('My Profile','foodzone'),
			'my_properties' => esc_html__('My Properties','foodzone'),
			'ad_property' => esc_html__('Add New Property','foodzone'),
			'pub' => esc_html__('Published','foodzone'),
			'pend' => esc_html__('Pending','foodzone'),
			'feat' => esc_html__('Featured','foodzone'),
			'exp' => esc_html__('Expired','foodzone'),
			'a_listing' => esc_html__('Search listing','foodzone'),
			'action' => esc_html__('Action','foodzone'),
			'price' => esc_html__('Price','foodzone'),
			'listed_in' => esc_html__('Listed In','foodzone'),
			'listing' => esc_html__('Listing','foodzone'),
			'publish' => esc_html__('Published Properties','foodzone'),
			'expired' => esc_html__('Expired Properties','foodzone'),
			'pending' => esc_html__('Pending Properties','foodzone'),
			'featured' => esc_html__('Featured Properties','foodzone'),
			'approval' => esc_html__(' Approval Required!','foodzone'),
			'approval_notify' => esc_html__('Waiting for admin approval. ','foodzone'),
			'agents' => esc_html__('Agents','foodzone'),
			'agent_name' => esc_html__('Agent Name','foodzone'),
			'display_name' => esc_html__('Display Name','foodzone'),
			'add_new_agent' => esc_html__('Add New Agent','foodzone'),
			'view_all_agent' => esc_html__('View All Agent','foodzone'),
			'username' => esc_html__('Username','foodzone'),
			'email' => esc_html__('Email','foodzone'),
			'agent_type' => esc_html__('Agent Type','foodzone'),
			'agent_type_req' => esc_html__('Agent type is required.','foodzone'),
			'contact_num' => esc_html__('Mobile Number','foodzone'),
			'pass' => esc_html__('Password','foodzone'),
			'u_required' => esc_html__('Username is required.','foodzone'),
			'email_required' => esc_html__('You have not given a correct e-mail address.','foodzone'),
			'pass_required' => esc_html__('Please choose a password with at least 3-12 characters.','foodzone'),
			'snd_email' => esc_html__('Send the new user an email about their account.','foodzone'),
			'search_agents' => esc_html__('Search agents...','foodzone'),
			'my_agents' => esc_html__('Agents','foodzone'),
			'agency_name' => esc_html__('Agency Name','foodzone'),
			'my_expiry' => esc_html__('Expire On','foodzone'),
			'my_mob' => esc_html__('Mobile Number','foodzone'),
			'my_whatsapp' => esc_html__('WhatsApp Number','foodzone'),
			'my_office' => esc_html__('Office Number','foodzone'),
			'my_fax' => esc_html__('Fax Number','foodzone'),
			'my_agency_lic' => esc_html__('License Number','foodzone'),
			'my_licence' => esc_html__('Agency License','foodzone'),
			'my_taxno' => esc_html__('Tax Number','foodzone'),
			'my_weburl' => esc_html__('Website Url','foodzone'),
			'my_agency_loc' => esc_html__('Agency Location','foodzone'),
			'my_about_agency' => esc_html__('About Agency','foodzone'),
			'my_about_agent' => esc_html__('About Agent','foodzone'),
			'my_about_yourself' => esc_html__('About Yourself','foodzone'),
			'buyer_loc' => esc_html__('Your Location','foodzone'),
			'my_fb' => esc_html__('Facebook URL','foodzone'),
			'my_tw' => esc_html__('Twitter URL','foodzone'),
			'my_ln' => esc_html__('LinkedIn URL','foodzone'),
			'my_insta' => esc_html__('Instagram URL','foodzone'),
			'my_you' => esc_html__('Youtube URL','foodzone'),
			'my_pint' => esc_html__('Pinterest URL','foodzone'),
			'my_addr' => esc_html__('Address','foodzone'),
			'my_coord' => esc_html__('Coordinates','foodzone'),
			'save_changes' => esc_html__('Save Changes','foodzone'),
			'agency_loc' => esc_html__('Agency Location','foodzone'),
			'agent_loc' => esc_html__('Agent Location','foodzone'),
			'social_media' => esc_html__('Social Media','foodzone'),
			'account_settings' => esc_html__('Account Settings','foodzone'),
			'my_profile' => esc_html__('My Profile','foodzone'),
			'feat_img' => esc_html__('Featured Image','foodzone'),
			'edit_pass' => esc_html__('Edit Password','foodzone'),
			'current_pass' => esc_html__('Current Password','foodzone'),
			'new_pass' => esc_html__('New Password','foodzone'),
			'conf_pass' => esc_html__('Confirm Password','foodzone'),
			'change_pass_btn' => esc_html__('Change My Password','foodzone'),
			'accn_delete' => esc_html__('Account Deletion','foodzone'),
			'accn_delete_msg' => esc_html__('If you want to delete your account your all data will be removed from this site.','foodzone'),
			'accn_delete_btn' => esc_html__('Delete My Account','foodzone'),
			'skype' => esc_html__('Skype','foodzone'),
			'working_hours' => esc_html__('Working Hours','foodzone'),
			'home' => esc_html__('Home','foodzone'),
			'page' => esc_html__('Page','foodzone'),
			'off' => esc_html__('of','foodzone'),
			'user_type' => esc_html__('User Type','foodzone'),
			'all_fields_error' 	=>   esc_html__('All fields are required.','foodzone'),
			'logout' 	=>   esc_html__('Logout','foodzone'),
			'signup' 	=>   esc_html__('Sign Up','foodzone'),
			'log' 	=>   esc_html__('Sign In','foodzone'),
			'or_reg' 	=>   esc_html__('Or Register With','foodzone'),
			'or_log' 	=>   esc_html__('Or Login With','foodzone'),
			'processing' 	=>   esc_html__('Processing...','foodzone'),
			'google' 	=>   esc_html__('Google','foodzone'),
			'fb' 	=>   esc_html__('Facebook','foodzone'),
			'details' 	=>   esc_html__('Detials','foodzone'),
			'price' 	=>   esc_html__('Price','foodzone'),
			'status' 	=>   esc_html__('Property Status','foodzone'),
			'prop_id' 	=>   esc_html__('Property ID','foodzone'),
			'prop_size' 	=>   esc_html__('Property Size','foodzone'),
			'prop_additional' 	=>   esc_html__('Additional Detials','foodzone'),
			'review_title' 	=>   esc_html__('Review Title','foodzone'),
			'your_review' 	=>   esc_html__('Your Review','foodzone'),
			'review_write' 	=>   esc_html__('Write a Review','foodzone'),
			'rating' 	=>   esc_html__('Rating','foodzone'),
			'beds' 	=>   esc_html__('Beds','foodzone'),
			'baths' 	=>   esc_html__('Baths','foodzone'),
			'size' 	=>   esc_html__('Size','foodzone'),
			'fav' 	=>   esc_html__('Favourite','foodzone'),
			'favorites' 	=>   esc_html__('Favorites','foodzone'),
			'fav_prop' 	=>   esc_html__('Favorites Properties','foodzone'),
			'compare' 	=>   esc_html__('Compare','foodzone'),
			'member_since' 	=>   esc_html__('Member Since','foodzone'),
			'featured_listings' 	=>   esc_html__('Featured Listings ','foodzone'),
			'display_name' 	=>   esc_html__('Display Name','foodzone'),
			'displayname_popover' 	=>   esc_html__('Agency Agent or Buyer display name','foodzone'),
			'get_directions' 	=>   esc_html__('Get Directions','foodzone'),
			'working_hours' 	=>   esc_html__('Working Hours','foodzone'),
			'prop_id' 	=>   esc_html__('Property ID','foodzone'),
			'near_me' 	=>   esc_html__('Near Me','foodzone'),
			'verified_listing' 	=>   esc_html__('Verified Listing','foodzone'),
			'total_published' 	=>   esc_html__('Total Published','foodzone'),
			'total_pending' 	=>   esc_html__('Total Pending','foodzone'),
			'total_featured' 	=>   esc_html__('Total Featured','foodzone'),
			'total_expired' 	=>   esc_html__('Total Expired','foodzone'),
			'total_views' 	=>   esc_html__('Views','foodzone'),
			'reviews' 	=>   esc_html__('Property Reviews','foodzone'),
			'profile_reviews' 	=>   esc_html__('Profile Reviews','foodzone'),
			'submitted' 	=>   esc_html__('Submitted Reviews','foodzone'),
			'received' 	=>   esc_html__('Received Reviews','foodzone'),
			'invoices' 	=>   esc_html__('Invoices','foodzone'),
			'invoice_status' 	=>   esc_html__('Status','foodzone'),
			'invoice_transaction' 	=>   esc_html__('Transaction ID','foodzone'),
			'invoice_total' 	=>   esc_html__('Total','foodzone'),
			'invoice_prop_id' 	=>   esc_html__('Property ID','foodzone'),
			'invoice_order_history' 	=>   esc_html__('Orders History','foodzone'),
			'invoice_method' 	=>   esc_html__('Method','foodzone'),
			'total_avg' 	=>   esc_html__('Total Average','foodzone'),
			'total_reviews' 	=>   esc_html__('Total Reviews','foodzone'),
			'total_stars' 	=>   esc_html__('Total Stars','foodzone'),
			'recommendations' 	=>   esc_html__('Recommendations','foodzone'),
			'welcome' 	=>   esc_html__('Welcome back,','foodzone'),
			'dashboard' 	=>   esc_html__('Dashboard','foodzone'),
			'recent_act' 	=>   esc_html__('Recent Activities','foodzone'),
	   );
	   return $localization;
    }
}
add_action( 'after_theme_setup', 'foodzone_localization' );

// Theme Error Messages
if( !function_exists('foodzone_localization_msgs') )
{
    function foodzone_localization_msgs()
	{
		global $messages;
        $messages = array
	    (
			'name_error' => esc_html__('Name field is required.','foodzone'),
	   		'mob_error' => esc_html__('Please enter a valid mobile number.','foodzone'),
			'email_error' 	=> esc_html__('You have not given a correct e-mail address.','foodzone'),
			'whatsapp_error' 	=> esc_html__('Please enter a WhatsApp number.','foodzone'),
			'office_no_error' 	=> esc_html__('Please enter a office number.','foodzone'),
			'fax_error' 	=> esc_html__('Fax number is required.','foodzone'),
			'license_error' 	=> esc_html__('License is required.','foodzone'),
			'tax_error' 	=> esc_html__('Tax number is required.','foodzone'),
			'web_url_error' 	=> esc_html__('Please enter a valid Website URL.','foodzone'),
			'loc_error' 	=>   esc_html__('Location is required.','foodzone'),
			'about_error' 	=>   esc_html__('About field is required.','foodzone'),
			'fb_error' 	=>   esc_html__('Please enter a valid Facebook URL.','foodzone'),
			'tw_error' 	=>   esc_html__('Please enter a valid Twitter URL.','foodzone'),
			'ln_error' 	=>   esc_html__('Please enter a valid LinkedIn URL.','foodzone'),
			'insta_error' 	=>   esc_html__('Please enter a valid Instagram URL.','foodzone'),
			'you_error' 	=>   esc_html__('Please enter a valid Youtube URL.','foodzone'),
			'pin_error' 	=>   esc_html__('Please enter a valid Pinterest URL.','foodzone'),
			'addr_error' 	=>   esc_html__('Address field is required.','foodzone'),
			'all_fields_error' 	=>   esc_html__('All fields are required.','foodzone'),
			'type_error' 	=>   esc_html__('Type fields is required.','foodzone'),
			'working_hours' 	=>   esc_html__('The working hours field is required.','foodzone'),
			'skype' 	=>   esc_html__('The skype field is required.','foodzone'),
			'position' 	=>   esc_html__('The position field is required.','foodzone'),
			//You have not answered all required fields
	   );
	   return $messages;
    }
}
add_action( 'after_theme_setup', 'foodzone_localization_msgs' );